name: Bump version

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  bump-version:
    permissions:
      contents: write
    if: startsWith(github.event.head_commit.message, 'bump:') == false
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          token: "${{ secrets.TEST_HIVEBOX_COMMITIZEN_TOKEN }}"

      - run: >-
          git fetch --no-tags --prune --depth=1 origin
          +refs/heads/*:refs/remotes/origin/*

      - name: Get changed folders
        id: changed_folders
        env:
          SHA: ${{ github.sha }}
        run: |
          export CHANGED_DIRS=$(git diff --name-only origin/main "$SHA" | awk -F/ '{print $1}' | sort -u)
          echo "Changed directories: $CHANGED_DIRS"
          echo "folders=$(echo "$CHANGED_DIRS" | xargs echo)" >> $GITHUB_OUTPUT

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@5b0848cd060263e24602d1eba03710e056ef7711 # v0.24.0
        with:
          working-directory: ${{ steps.changed_folders.outputs.folders }}
          github_token: ${{ secrets.TEST_HIVEBOX_COMMITIZEN_TOKEN }}
          changelog_increment_filename: body.md
          check_consistency: true

      - name: Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
